#include "mcv_platform.h"
#include "all_components.h"

DECL_OBJ_MANAGER(CEntity, "entity");
DECL_OBJ_MANAGER(TCompTransform, "transform");
DECL_OBJ_MANAGER(TCompLife, "life");
DECL_OBJ_MANAGER(TCompName, "name");
DECL_OBJ_MANAGER(TCompMesh, "mesh");
DECL_OBJ_MANAGER(TCompCamera, "camera");
DECL_OBJ_MANAGER(TCompCollider, "collider");
DECL_OBJ_MANAGER(TCompRigidBody, "rigidbody");
DECL_OBJ_MANAGER(TCompStaticBody, "staticbody");
DECL_OBJ_MANAGER(TCompPlayerController, "playerController");
DECL_OBJ_MANAGER(TCompPlayerPivotController, "playerPivotController");
DECL_OBJ_MANAGER(TCompCameraPivotController, "cameraPivotController");
DECL_OBJ_MANAGER(TCompThirdPersonCameraController, "thirdPersonCameraController");
DECL_OBJ_MANAGER(TCompAABB, "aabb");
DECL_OBJ_MANAGER(TCompDistanceJoint, "distanceJoint");
DECL_OBJ_MANAGER(TCompDirectionalLight, "directionalLight");
DECL_OBJ_MANAGER(TCompAmbientLight, "ambientLight");
DECL_OBJ_MANAGER(TCompPointLight, "pointLight");
DECL_OBJ_MANAGER(TCompColliderMesh, "colliderMesh");
DECL_OBJ_MANAGER(TCompAiFsmBasic, "aiFSMBasic");
DECL_OBJ_MANAGER(TCompEnemyController, "enemyController");
DECL_OBJ_MANAGER(TCompNeedle, "needle");
DECL_OBJ_MANAGER(TCompRope, "rope");
DECL_OBJ_MANAGER(TCompUnityCharacterController, "unityCharacterController");