#include "mcv_platform.h"
#include "all_components.h"

DECL_OBJ_MANAGER(CEntity, "entity");
DECL_OBJ_MANAGER(TCompTransform, "transform");
DECL_OBJ_MANAGER(TCompLife, "life");
DECL_OBJ_MANAGER(TCompName, "name");
DECL_OBJ_MANAGER(TCompMesh, "mesh");
DECL_OBJ_MANAGER(TCompMeshCollider, "meshCollider");
DECL_OBJ_MANAGER(TCompCamera, "camera");
DECL_OBJ_MANAGER(TCompCollider, "collider");
DECL_OBJ_MANAGER(TCompRigidBody, "rigidbody");
DECL_OBJ_MANAGER(TCompStaticBody, "staticbody");
DECL_OBJ_MANAGER(TCompPlayerController, "playerController");
DECL_OBJ_MANAGER(TCompPlayerPivotController, "playerPivotController");
DECL_OBJ_MANAGER(TCompCameraPivotController, "cameraPivotController");
DECL_OBJ_MANAGER(TCompThirdPersonCameraController, "thirdPersonCameraController");
DECL_OBJ_MANAGER(TCompAABB, "aabb");
DECL_OBJ_MANAGER(TCompDistanceJoint, "distanceJoint");
DECL_OBJ_MANAGER(TCompDirectionalLight, "directionalLight");
DECL_OBJ_MANAGER(TCompAmbientLight, "ambientLight");
DECL_OBJ_MANAGER(TCompPointLight, "pointLight");
